name: myspeed
services:
    myspeed:
        image: germannewsmaker/myspeed
        container_name: MySpeed
        restart: unless-stopped
        ports:
            - 5216:5216
        volumes:
            - ./myspeed:/myspeed/data
